### ISSUE TITLE
Revise 2.g-k. authentication 

### ISSUE THREAD

**Issue by BenWilson-Mozilla** [cabforum/netsec#16]
A comment was received that section 2.k.2 of the NCSSRs "Cannot be leveraged for a denial of service attack" needs to be clarified.

**Comment by clintwilson** [comment]
Revise how the NSRs set requirements for passwords, credentials, and account lockout. This will be helped by revising how the NSRs refer to access in general.

**Comment by clintwilson** [comment]
2.k and the language about denial of service attacks was specifically addressed in #33
