### ISSUE TITLE
Replace "Zones" with more specific terminology

### ISSUE THREAD

**Issue by BenWilson-Mozilla** [cabforum/netsec#17]
Currently, the use of the term "zones" causes confusion because it can mean either a physical zone or a logical/network zone.

**Comment by BenWilson-Mozilla** [comment]
Secure Facility or Secure Room :  A physical area protected by physical access controls.
Secure Network or Secure Segments :  A logical space or collection of systems

**Comment by clintwilson** [comment]
Addressed in #33
