### ISSUE TITLE
NetSec: Clarify software enforcing bridging is insufficient for network segmentation

### ISSUE THREAD

**Issue by tomrittervg** [cabforum/netsec#24]
@sleevi raised the point that it would be good to clarify 1a to avoid 'something stupid' where that would be any sort of OS or software-enforced network bridging (host based stacks doing VLAN tagging). Network segmentation should be enforced by outside hardware (like a switch or an airgap)

**Comment by clintwilson** [comment]
Updated in Section 1.1.1.1 in #33
