### ISSUE TITLE
Clarify scope between physical and logical access

### ISSUE THREAD

**Issue by dja852** [cabforum/netsec#31]
@clintwilson 

In the following requirements, it is unclear whether the intent is for logical access, physical access, or both. I would recommend explicitly clarifying this for each requirement so there is no confusion.

https://github.com/cabforum/netsec/blob/a256f31ac277204a348106b6bfb511147baa23c6/docs/NSR.md?plain=1#L286-L315
https://github.com/cabforum/netsec/blob/a256f31ac277204a348106b6bfb511147baa23c6/docs/NSR.md?plain=1#L325-L330

**Comment by clintwilson** [comment]
In 2.2.1.3, I used "all access"; do you think updating 2.2.1 and 2.2.3 likewise would address the concern (i.e. adding "all" in front of "access")?

**Comment by dja852** [comment]
I would do that, but I can also see arguments (and have heard arguments) that 'all access' may not include physical. If the intent is for physical to be included, then I would be as explicit as you can.

One suggestion would between these lines:
https://github.com/cabforum/netsec/blob/a256f31ac277204a348106b6bfb511147baa23c6/docs/NSR.md?plain=1#L267-L269
you could add a clarification of something like `Within this section 2, references to 'access' include all physical and logical access mechanisms unless otherwise specified.`

**Comment by clintwilson** [comment]
Addressed in #33
