### ISSUE TITLE
Separate the requirements for offline/air-gapped CAs and online CAs

### ISSUE THREAD

**Issue by BenWilson-Mozilla** [cabforum/netsec#5]
There are requirements that don't apply to offline/air-gapped CAs because they are not networked.  
See https://docs.google.com/document/d/1cnb1JNuckOjo5UbQdWVtU5t-PpS2HLt7/edit?usp=sharing&ouid=117503639592111535599&rtpof=true&sd=true

**Comment by clintwilson** [comment]
Duplicate of https://github.com/cabforum/netsec/issues/28
